resolver: lts-10.5

packages:
  - mismi-p
#- mismi-autoscaling
#- mismi-autoscaling-core
#- mismi-autoscaling-core/test
#- mismi-autoscaling/test
#- mismi-cli
  - mismi-core
  - mismi-core/test
#- mismi-dynamodb
#- mismi-ec2
#- mismi-ec2-core
#- mismi-ec2-core/test
#- mismi-iam-core
  - mismi-kernel
  - mismi-kernel/test
#- mismi-openssl
#- mismi-s3
#- mismi-s3-core
#- mismi-s3-core/test
#- mismi-s3/test
#- mismi-sqs
#- mismi-sqs-core
#- mismi-sqs-core/test
#- mismi-sqs/test

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
#extra-deps:
#  - lib/x/x-eithert
#  - lib/x/x-exception
